/* global window */
/* Work / Case Studies — shared data */

window.BW_CASES = [
  {
    slug: "oneil-digital-solutions",
    no: "01",
    client: "O'Neil Digital Solutions",
    year: "2024",
    industry: "Customer Communications",
    pillar: "Brand · Demand",
    pillars: ["Brand", "Demand"],
    outcome: "Pipeline",
    tags: ["Brand", "Demand", "Decade-long"],
    pull: "Redefining a world-class brand.",
    lede: "A near-decade partnership with O'Neil to evolve them into the nation's leading Customer Communications Management and CX provider — and to give the ONEsuite platform a story enterprise buyers and analysts both believed.",
    tone: "linear-gradient(135deg, #0E1726 0%, #14100C 100%)",
    bigStat: { v: "5B+", k: "Digital pages delivered, 2024" },
    metrics: [
      { v: "5B+", k: "Pages delivered" },
      { v: "4×", k: "Aspire leader, consecutive" },
      { v: "10", k: "Capabilities engaged" },
    ],
    duration: "Decade-long partnership",
    team: ["Strategy", "Brand", "Lifecycle", "Lab"],
    imagery: "photo",
    heroImage: "assets/cases/oneil/hero.jpg",
    featuredBg: "linear-gradient(45deg, #0A223C 0%, #1A4978 50%, #2C7A8C 100%)",
    clientLogo: "assets/cases/oneil/logo.webp",
    clientLogoInvert: true,
    clientLogoHeight: 72,
    href: "case-oneil.html",
    featured: true,
  },
  {
    slug: "archdiocese-of-detroit",
    no: "02",
    client: "Archdiocese of Detroit",
    year: "2017",
    industry: "Faith · Non-Profit",
    pillar: "Brand",
    pillars: ["Brand"],
    outcome: "Brand",
    tags: ["Brand", "Identity", "Faith"],
    pull: "A 200-year institution, refit for a missionary century.",
    lede: "A multi-year partnership with the Archdiocese of Detroit to translate Archbishop Vigneron's pastoral letter Unleash the Gospel into a brand foundation, heraldic identity, and publishing system carried by 1.3 million Catholics across southeast Michigan.",
    tone: "linear-gradient(135deg, #0c3b60 0%, #a93439 100%)",
    bigStat: { v: "1.3M", k: "Catholics reached, 6-county region" },
    metrics: [
      { v: "1.3M", k: "Catholics reached" },
      { v: "200+", k: "Parishes adopting" },
      { v: "6",    k: "Capabilities engaged" },
    ],
    duration: "Multi-year engagement",
    team: ["Strategy", "Brand", "Lifecycle"],
    imagery: "photo",
    heroImage: "assets/cases/archdiocese-detroit/hero.jpg",
    featuredBg: "linear-gradient(90deg, #082841 0%, #0c3b60 55%, #a93439 100%)",
    clientLogo: "assets/cases/archdiocese-detroit/logo.svg",
    clientLogoInvert: true,
    clientLogoHeight: 72,
    href: "case-archdiocese-detroit.html",
  },
  {
    slug: "calyx",
    no: "03",
    client: "Calyx",
    year: "2024",
    industry: "Managed IT Services",
    pillar: "Brand · Demand",
    pillars: ["Brand", "Demand"],
    outcome: "Pipeline",
    tags: ["Brand", "Demand", "MSP"],
    pull: "An MSP that lets small and mid-market businesses act enterprise-grade.",
    lede: "A multi-year partnership with Calyx — a managed services provider deploying enterprise-grade IT for ambitious small and mid-market businesses — to build a brand foundation, identity system, and the \"With Calyx, you can\" campaign that match the size of their ambition.",
    tone: "linear-gradient(135deg, #3a4754 0%, #e95d15 100%)",
    bigStat: { v: "—", k: "Headline metric awaiting client release" },
    metrics: [
      { v: "9", k: "Capabilities engaged" },
      { v: "3", k: "Sub-brands" },
      { v: "—", k: "Pipeline lift (pending)" },
    ],
    duration: "Multi-year engagement",
    team: ["Strategy", "Brand", "Demand"],
    imagery: "photo",
    heroImage: "assets/cases/calyx/hero.jpg",
    featuredBg: "linear-gradient(90deg, #2a323b 0%, #3a4754 55%, #e95d15 100%)",
    clientLogo: "assets/cases/calyx/logo.svg",
    clientLogoInvert: true,
    clientLogoHeight: 60,
    href: "case-calyx.html",
  },
  {
    slug: "tt-electronics",
    no: "04",
    client: "TT Electronics IMS",
    year: "2018",
    industry: "Electronics Manufacturing",
    pillar: "Brand · Demand",
    pillars: ["Brand", "Demand"],
    outcome: "Brand",
    tags: ["Brand", "Tagline", "Repositioning"],
    pull: "Your Vision. Integrated.",
    lede: "TT Electronics IMS lived inside its parent's shadow. We built the brand foundation, named the tagline, and shipped a multilingual site that tripled traffic in twelve months.",
    tone: "linear-gradient(135deg, #2C7DB8 0%, #082240 100%)",
    bigStat: { v: "+300%", k: "Site traffic, twelve months" },
    metrics: [
      { v: "+300%", k: "Traffic lift" },
      { v: "5", k: "Languages live" },
      { v: "4", k: "Vertical campaigns" },
    ],
    duration: "Multi-year",
    team: ["Strategy", "Brand", "Demand"],
    imagery: "photo",
    heroImage: "assets/cases/tt-electronics/hero.jpg",
    featuredBg: "linear-gradient(135deg, #1A4F7A 0%, #0F3D66 45%, #082240 100%)",
    clientLogo: "assets/cases/tt-electronics/TT-logo-mono.svg",
    clientLogoInvert: true,
    clientLogoHeight: 52,
    href: "case-tt-electronics.html",
  },
  {
    slug: "afimac",
    no: "05",
    client: "AFIMAC",
    year: "2025",
    industry: "Labor Services",
    pillar: "Brand · Demand",
    pillars: ["Brand", "Demand"],
    outcome: "Brand",
    tags: ["Brand", "Demand", "Category Creation"],
    pull: "Stand Ready.",
    lede: "AFIMAC was well known in the strike-security space, and virtually invisible in the broader temporary-labor market. We built the brand, named a new service category (CSTL), and the demand engine that introduces a long-cycle service to buyers who didn't know it existed.",
    tone: "linear-gradient(135deg, #0F3D66 0%, #2C7DB8 100%)",
    bigStat: { v: "CSTL", k: "New service category, named & owned" },
    metrics: [
      { v: "CSTL", k: "Category coined" },
      { v: "9",    k: "Capabilities engaged" },
      { v: "<1yr", k: "To brand-led pipeline" },
    ],
    duration: "Active engagement",
    team: ["Strategy", "Brand", "Demand", "Lifecycle"],
    imagery: "photo",
    heroImage: "assets/cases/afimac/hero-traveler.jpg",
    featuredBg: "linear-gradient(45deg, #0a223c 0%, #0F3D66 50%, #2C7DB8 100%)",
    clientLogo: "assets/cases/afimac/AFIMAC-logo.svg",
    clientLogoInvert: true,
    clientLogoHeight: 56,
    href: "case-afimac.html",
  },
  {
    slug: "sacred-heart-major-seminary",
    no: "06",
    client: "Sacred Heart Major Seminary",
    year: "2023",
    industry: "Faith · Higher Education",
    pillar: "Brand",
    pillars: ["Brand"],
    outcome: "Brand",
    tags: ["Brand", "Identity", "Faith"],
    pull: "A century-old seminary, set on fire for a new evangelization.",
    lede: "Sacred Heart Major Seminary is a Catholic institution of higher learning associated with the Archdiocese of Detroit — a leading center of the New Evangelization. Boondock Walker shaped the brand foundation, identity system, and guidelines that now unify their communications across recruitment, donor relations, and the seminary's growing national footprint.",
    tone: "linear-gradient(135deg, #5A0F1D 0%, #b51e3d 100%)",
    bigStat: { v: "Heart.", k: "Mind. Mission." },
    metrics: [
      { v: "5", k: "Capabilities engaged" },
      { v: "Heart.", k: "Mind. Mission." },
    ],
    duration: "Multi-year engagement",
    team: ["Strategy", "Brand"],
    imagery: "photo",
    heroImage: "assets/cases/sacred-heart/hero.jpg",
    featuredBg: "linear-gradient(45deg, #3A0E14 0%, #5A0F1D 50%, #b51e3d 100%)",
    clientLogo: "assets/cases/sacred-heart/academic-mark.png",
    clientLogoInvert: true,
    clientLogoHeight: 64,
    href: "case-sacred-heart.html",
  },
  {
    slug: "envera",
    no: "07",
    client: "Envera",
    year: "2024",
    industry: "Healthcare · Engagement",
    pillar: "Brand",
    pillars: ["Brand"],
    outcome: "Brand",
    tags: ["Brand", "Identity", "Healthcare"],
    pull: "Find your truth.",
    lede: "Following two acquisitions, Envera engaged Boondock Walker to lead brand foundation, identity, website, and sales tools on an accelerated timeline — landing the \"Simple Truths\" campaign that defines their value to healthcare providers.",
    tone: "linear-gradient(135deg, #f7921e 0%, #f06c36 100%)",
    bigStat: { v: "Find truth.", k: "Provide insight. Simplify delivery." },
    metrics: [
      { v: "7", k: "Capabilities engaged" },
      { v: "2", k: "Acquisitions integrated" },
    ],
    duration: "Accelerated launch",
    team: ["Strategy", "Brand"],
    imagery: "photo",
    heroImage: "assets/cases/envera/hero.jpg",
    featuredBg: "linear-gradient(45deg, #c25018 0%, #f06c36 50%, #f7921e 100%)",
    clientLogo: "assets/cases/envera/envera-logo.svg",
    clientLogoHeight: 56,
    href: "case-envera.html",
  },
  {
    slug: "central-kitchen",
    no: "08",
    client: "Central Kitchen",
    year: "2024",
    industry: "Food · Education",
    pillar: "Brand",
    pillars: ["Brand"],
    outcome: "Brand",
    tags: ["Brand", "Website", "Education"],
    pull: "Where craft food concepts take off.",
    lede: "Central Kitchen is a craft food business accelerator and innovation hub. In partnership with our friends at Muse, Boondock Walker built the brand strategy, a new company website, and an online \"Craft Food Classroom\" — the platform Central Kitchen uses to recruit, teach, and connect craft food entrepreneurs.",
    tone: "linear-gradient(135deg, #201c1d 0%, #ab8f50 100%)",
    bigStat: { v: "Craft.", k: "Community. Classroom." },
    metrics: [
      { v: "3", k: "Capabilities engaged" },
      { v: "1", k: "Online Classroom" },
    ],
    duration: "Multi-phase engagement",
    team: ["Strategy", "Brand"],
    imagery: "photo",
    heroImage: "assets/cases/central-kitchen/hero.jpg",
    featuredBg: "linear-gradient(45deg, #0F0D0E 0%, #201c1d 50%, #ab8f50 100%)",
    clientLogo: "assets/cases/central-kitchen/logo.svg",
    clientLogoHeight: 72,
    href: "case-central-kitchen.html",
  },
];
