/* global window */
/* Work / Case Studies — shared data */

window.BW_CASES = [
  {
    slug: "oneil-digital-solutions",
    no: "01",
    client: "O'Neil Digital Solutions",
    year: "2024",
    industry: "Customer Communications",
    pillar: "Brand · Demand",
    pillars: ["Brand", "Demand"],
    outcome: "Pipeline",
    tags: ["Brand", "Demand", "Decade-long"],
    pull: "Redefining a world-class brand.",
    lede: "A near-decade partnership with O'Neil to evolve them into the nation's leading Customer Communications Management and CX provider — and to give the ONEsuite platform a story enterprise buyers and analysts both believed.",
    tone: "linear-gradient(135deg, #0E1726 0%, #14100C 100%)",
    bigStat: { v: "5B+", k: "Digital pages delivered, 2024" },
    metrics: [
      { v: "5B+", k: "Pages delivered" },
      { v: "4×", k: "Aspire leader, consecutive" },
      { v: "10", k: "Capabilities engaged" },
    ],
    duration: "Decade-long partnership",
    team: ["Strategy", "Brand", "Lifecycle", "Lab"],
    imagery: "photo",
    heroImage: "assets/cases/oneil/hero.jpg",
    featuredBg: "linear-gradient(90deg, #061528 0%, #0A1428 55%, #001F3D 100%)",
    clientLogo: "assets/cases/oneil/logo.webp",
    clientLogoInvert: true,
    clientLogoHeight: 72,
    href: "case-oneil.html",
    featured: true,
  },
  {
    slug: "archdiocese-of-detroit",
    no: "02",
    client: "Archdiocese of Detroit",
    year: "2017",
    industry: "Faith · Non-Profit",
    pillar: "Brand",
    pillars: ["Brand"],
    outcome: "Brand",
    tags: ["Brand", "Identity", "Faith"],
    pull: "A 200-year institution, refit for a missionary century.",
    lede: "A multi-year partnership with the Archdiocese of Detroit to translate Archbishop Vigneron's pastoral letter Unleash the Gospel into a brand foundation, heraldic identity, and publishing system carried by 1.3 million Catholics across southeast Michigan.",
    tone: "linear-gradient(135deg, #0c3b60 0%, #a93439 100%)",
    bigStat: { v: "1.3M", k: "Catholics reached, 6-county region" },
    metrics: [
      { v: "1.3M", k: "Catholics reached" },
      { v: "200+", k: "Parishes adopting" },
      { v: "6",    k: "Capabilities engaged" },
    ],
    duration: "Multi-year engagement",
    team: ["Strategy", "Brand", "Lifecycle"],
    imagery: "photo",
    heroImage: "assets/cases/archdiocese-detroit/hero.jpg",
    featuredBg: "linear-gradient(90deg, #082841 0%, #0c3b60 55%, #a93439 100%)",
    clientLogo: "assets/cases/archdiocese-detroit/logo.svg",
    clientLogoInvert: true,
    clientLogoHeight: 72,
    href: "case-archdiocese-detroit.html",
  },
  {
    slug: "walker-bros",
    no: "03",
    client: "Walker Bros.",
    year: "2026",
    industry: "Manufacturing",
    pillar: "Brand · Demand",
    pillars: ["Brand", "Demand"],
    outcome: "Pipeline",
    tags: ["Brand", "Demand", "Wholesale → Direct"],
    pull: "A 70-year wholesale brand learns to close direct.",
    lede: "Walker Bros. had spent seven decades selling through distributors. When the Q4 forecast slipped for the third year running, the third-generation owner asked us to build the brand and the system that would let them sell, ship, and renew without a middleman in the room.",
    tone: "linear-gradient(135deg, #C44A2A 0%, #7A2810 100%)",
    bigStat: { v: "+148%", k: "SQL volume, six months" },
    metrics: [
      { v: "+148%", k: "SQL volume" },
      { v: "$2.4M", k: "Pipeline added" },
      { v: "37%", k: "Reorder rate" },
    ],
    duration: "9 months",
    team: ["Strategy", "Brand", "Lifecycle", "AI"],
    imagery: "abstract",
  },
  { slug: "halberd-tools", no: "04", client: "Halberd Tools", year: "2025", industry: "Manufacturing", pillar: "Lab · Demand", pillars: ["Lab", "Demand"], outcome: "Efficiency", tags: ["Lab", "AI Desk-rep"], pull: "A trained AI desk-rep that sounds like the founder.", lede: "Halberd's inbound was choking the sales team. We trained a custom desk-rep on five years of founder transcripts.", tone: "linear-gradient(135deg, #2E4626 0%, #14100C 100%)", bigStat: { v: "$0.42", k: "Cost per qualified lead" }, metrics: [{ v: "2,140", k: "SQL routed" }, { v: "$0.42", k: "Cost / lead" }, { v: "94%", k: "Voice accuracy" }], duration: "4 months", team: ["AI", "Lifecycle"], imagery: "screenshot" },
  { slug: "north-by-northeast", no: "05", client: "North-by-Northeast", year: "2025", industry: "Pro services", pillar: "Brand", pillars: ["Brand"], outcome: "Brand", tags: ["Brand", "Repositioning"], pull: "Repositioned mid-market, doubled enterprise close rate.", lede: "A 40-person consultancy fighting for SMB scraps. We pulled them up-market with a story enterprise buyers actually believed.", tone: "linear-gradient(135deg, #5E2638 0%, #2A0F18 100%)", bigStat: { v: "2.1×", k: "Enterprise close rate" }, metrics: [{ v: "2.1×", k: "Close rate" }, { v: "37 days", k: "Sales cycle" }, { v: "+$890K", k: "ACV" }], duration: "6 months", team: ["Strategy", "Brand"], imagery: "abstract" },
  { slug: "field-and-co", no: "06", client: "Field & Co.", year: "2025", industry: "DTC", pillar: "Brand · Lab", pillars: ["Brand", "Lab"], outcome: "Retention", tags: ["Brand", "Lab"], pull: "Retention copy that finally sounded human, written by a machine.", lede: "An outdoor goods brand whose lifecycle emails read like a spreadsheet. We rebuilt the voice and trained a generator to keep it consistent across 90 sequences.", tone: "linear-gradient(135deg, #C8962B 0%, #7A5A12 100%)", bigStat: { v: "+38%", k: "Repeat purchase, Y/Y" }, metrics: [{ v: "+38%", k: "Repeat purchase" }, { v: "−62%", k: "Unsubscribes" }, { v: "4.1×", k: "Email LTV" }], duration: "5 months", team: ["Brand", "AI", "Lifecycle"], imagery: "photo" },
  { slug: "marrow-health", no: "07", client: "Marrow Health", year: "2024", industry: "Healthcare", pillar: "Demand", pillars: ["Demand"], outcome: "Pipeline", tags: ["Demand"], pull: "Stitched the gap between specialist referral and patient activation.", lede: "Marrow's referrals were leaking out the back door. We mapped the lifecycle, found the holes, and rebuilt the activation track.", tone: "linear-gradient(135deg, #3F6976 0%, #1A2D33 100%)", bigStat: { v: "−54%", k: "Referral leakage" }, metrics: [{ v: "−54%", k: "Leakage" }, { v: "+71%", k: "Activation" }, { v: "21 days", k: "Time-to-care" }], duration: "8 months", team: ["Lifecycle", "Strategy"], imagery: "abstract" },
  { slug: "praxis-fintech", no: "08", client: "Praxis", year: "2024", industry: "Fintech", pillar: "Brand", pillars: ["Brand"], outcome: "Brand", tags: ["Brand", "Naming"], pull: "Renamed, repositioned, and walked into Series B with a story.", lede: "Praxis came to us six weeks before a fundraise with a name nobody could pronounce and a deck that said nothing.", tone: "linear-gradient(135deg, #14100C 0%, #3A2A1E 100%)", bigStat: { v: "$24M", k: "Series B closed" }, metrics: [{ v: "$24M", k: "Series B" }, { v: "8 weeks", k: "Sprint" }, { v: "3", k: "Term sheets" }], duration: "8 weeks", team: ["Strategy", "Brand"], imagery: "abstract" },
  { slug: "halyard", no: "09", client: "Halyard", year: "2024", industry: "B2B SaaS", pillar: "Demand · Lab", pillars: ["Demand", "Lab"], outcome: "Pipeline", tags: ["Demand", "Lab"], pull: "An intent score that the sales team actually trusted.", lede: "We threw out the lead-scoring rubric and built something the AEs would defend in a pipeline review.", tone: "linear-gradient(135deg, #C44A2A 0%, #5E2638 100%)", bigStat: { v: "3.4×", k: "MQL → SQL conversion" }, metrics: [{ v: "3.4×", k: "MQL→SQL" }, { v: "−47%", k: "False positives" }, { v: "+$1.8M", k: "Pipeline" }], duration: "6 months", team: ["AI", "Lifecycle"], imagery: "screenshot" },
  { slug: "northbeam", no: "10", client: "Northbeam", year: "2023", industry: "B2B SaaS", pillar: "Brand", pillars: ["Brand"], outcome: "Brand", tags: ["Brand"], pull: "From category-of-one to category-leader in eighteen months.", lede: "We didn't invent their category. We helped them claim it loud enough that the analysts had to listen.", tone: "linear-gradient(135deg, #2E4626 0%, #C8962B 100%)", bigStat: { v: "#1", k: "G2 grid placement" }, metrics: [{ v: "#1", k: "G2 grid" }, { v: "+210%", k: "Branded search" }, { v: "12", k: "Tier-1 mentions" }], duration: "18 months", team: ["Strategy", "Brand", "Lifecycle"], imagery: "photo" },
  { slug: "bowline", no: "11", client: "Bowline", year: "2023", industry: "Pro services", pillar: "Lab", pillars: ["Lab"], outcome: "Efficiency", tags: ["Lab"], pull: "Triage AI that turned 400 weekly inquiries into 40 calls worth taking.", lede: "Bowline's inbox was a graveyard. We built a triage layer that read every inbound, qualified it, and routed only the live ones to a human.", tone: "linear-gradient(135deg, #C8962B 0%, #14100C 100%)", bigStat: { v: "10×", k: "AE focus ratio" }, metrics: [{ v: "10×", k: "AE focus" }, { v: "92%", k: "Triage accuracy" }, { v: "−38hrs", k: "Per AE / mo" }], duration: "3 months", team: ["AI"], imagery: "screenshot" },
  { slug: "atlas-mfg", no: "12", client: "Atlas Mfg.", year: "2023", industry: "Manufacturing", pillar: "Brand · Demand", pillars: ["Brand", "Demand"], outcome: "Pipeline", tags: ["Brand", "Demand"], pull: "A 110-year industrial brand learns to talk to engineers, not procurement.", lede: "Atlas had been writing brochures for the buyer who signs the PO. We rewrote everything for the engineer who specs the part.", tone: "linear-gradient(135deg, #7A2810 0%, #14100C 100%)", bigStat: { v: "+86%", k: "Spec-in rate" }, metrics: [{ v: "+86%", k: "Spec-in" }, { v: "+$4.1M", k: "Pipeline" }, { v: "47%", k: "Engineer NPS" }], duration: "12 months", team: ["Strategy", "Brand", "Lifecycle"], imagery: "abstract" },
  { slug: "quarry", no: "13", client: "Quarry", year: "2022", industry: "B2B SaaS", pillar: "Demand", pillars: ["Demand"], outcome: "Retention", tags: ["Demand"], pull: "A retention motion built on real usage signals, not a renewal calendar.", lede: "Quarry's customers were renewing on autopilot — until they didn't. We rebuilt the playbook around the moment of truth, not the contract date.", tone: "linear-gradient(135deg, #3F6976 0%, #5E2638 100%)", bigStat: { v: "+12pts", k: "Net revenue retention" }, metrics: [{ v: "+12pts", k: "NRR" }, { v: "−43%", k: "Logo churn" }, { v: "+$2.2M", k: "Expansion" }], duration: "7 months", team: ["Lifecycle", "Strategy"], imagery: "screenshot" },
  { slug: "greylock-press", no: "14", client: "Greylock Press", year: "2022", industry: "DTC", pillar: "Brand", pillars: ["Brand"], outcome: "Brand", tags: ["Brand"], pull: "A 30-year publishing house, refit for the post-Substack world.", lede: "An independent press whose audience was aging out and whose acquisition channels were collapsing. We built them a brand and a subscription motion that meet readers where they actually are now.", tone: "linear-gradient(135deg, #5E2638 0%, #C44A2A 100%)", bigStat: { v: "+14K", k: "Paid subscribers" }, metrics: [{ v: "+14K", k: "Subscribers" }, { v: "+340%", k: "Direct sales" }, { v: "62%", k: "Sub. retention" }], duration: "10 months", team: ["Strategy", "Brand", "Lifecycle"], imagery: "photo" },
];
